/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_newline = 2,
  sym_comment = 3,
  anon_sym_COLON = 4,
  anon_sym_DOT = 5,
  sym_directive_keyword = 6,
  anon_sym_LBRACE = 7,
  anon_sym_COMMA = 8,
  anon_sym_RBRACE = 9,
  sym_struct_keyword = 10,
  anon_sym_EQ = 11,
  sym_mnemonic = 12,
  sym_hex_number = 13,
  sym_address = 14,
  anon_sym_AT = 15,
  sym_char_literal = 16,
  sym_string_literal = 17,
  sym_register = 18,
  sym_operator = 19,
  anon_sym_LPAREN = 20,
  anon_sym_RPAREN = 21,
  anon_sym_AMP = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  sym_source_file = 27,
  sym__line = 28,
  sym__statement = 29,
  sym_label = 30,
  sym_local_label = 31,
  sym_directive = 32,
  sym_struct_directive = 33,
  sym_struct_field = 34,
  sym__dir_tail = 35,
  sym_instruction = 36,
  sym_operands = 37,
  sym__operand = 38,
  sym_local_label_ref = 39,
  sym_symbol_ref = 40,
  sym_paren_expr = 41,
  sym_bracket_expr = 42,
  sym_cast = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_directive_repeat1 = 45,
  aux_sym_struct_directive_repeat1 = 46,
  aux_sym_operands_repeat1 = 47,
  aux_sym_paren_expr_repeat1 = 48,
  aux_sym_bracket_expr_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [sym_directive_keyword] = "directive_keyword",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [sym_struct_keyword] = "struct_keyword",
  [anon_sym_EQ] = "=",
  [sym_mnemonic] = "mnemonic",
  [sym_hex_number] = "hex_number",
  [sym_address] = "address",
  [anon_sym_AT] = "@",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [sym_register] = "register",
  [sym_operator] = "operator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AMP] = "&",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_local_label] = "local_label",
  [sym_directive] = "directive",
  [sym_struct_directive] = "struct_directive",
  [sym_struct_field] = "struct_field",
  [sym__dir_tail] = "_dir_tail",
  [sym_instruction] = "instruction",
  [sym_operands] = "operands",
  [sym__operand] = "_operand",
  [sym_local_label_ref] = "local_label_ref",
  [sym_symbol_ref] = "symbol_ref",
  [sym_paren_expr] = "paren_expr",
  [sym_bracket_expr] = "bracket_expr",
  [sym_cast] = "cast",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
  [aux_sym_struct_directive_repeat1] = "struct_directive_repeat1",
  [aux_sym_operands_repeat1] = "operands_repeat1",
  [aux_sym_paren_expr_repeat1] = "paren_expr_repeat1",
  [aux_sym_bracket_expr_repeat1] = "bracket_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_directive_keyword] = sym_directive_keyword,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_struct_keyword] = sym_struct_keyword,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_mnemonic] = sym_mnemonic,
  [sym_hex_number] = sym_hex_number,
  [sym_address] = sym_address,
  [anon_sym_AT] = anon_sym_AT,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_register] = sym_register,
  [sym_operator] = sym_operator,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_local_label] = sym_local_label,
  [sym_directive] = sym_directive,
  [sym_struct_directive] = sym_struct_directive,
  [sym_struct_field] = sym_struct_field,
  [sym__dir_tail] = sym__dir_tail,
  [sym_instruction] = sym_instruction,
  [sym_operands] = sym_operands,
  [sym__operand] = sym__operand,
  [sym_local_label_ref] = sym_local_label_ref,
  [sym_symbol_ref] = sym_symbol_ref,
  [sym_paren_expr] = sym_paren_expr,
  [sym_bracket_expr] = sym_bracket_expr,
  [sym_cast] = sym_cast,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
  [aux_sym_struct_directive_repeat1] = aux_sym_struct_directive_repeat1,
  [aux_sym_operands_repeat1] = aux_sym_operands_repeat1,
  [aux_sym_paren_expr_repeat1] = aux_sym_paren_expr_repeat1,
  [aux_sym_bracket_expr_repeat1] = aux_sym_bracket_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_struct_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_number] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_local_label] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__dir_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_operands] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym_local_label_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_cast] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operands_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paren_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bracket_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_mnemonic = 2,
  field_name = 3,
  field_object = 4,
  field_property = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
  [1] =
    {field_mnemonic, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_name, 1},
  [4] =
    {field_keyword, 0},
    {field_name, 1},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_object, 3},
    {field_property, 5},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 7,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 19,
  [38] = 25,
  [39] = 39,
  [40] = 20,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 55,
  [70] = 70,
  [71] = 71,
  [72] = 63,
  [73] = 61,
  [74] = 71,
  [75] = 64,
  [76] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\n', 9,
        '\r', 1,
        '"', 2,
        '$', 7,
        '&', 32,
        '\'', 4,
        '(', 30,
        ')', 31,
        ',', 15,
        '.', 13,
        ':', 12,
        ';', 10,
        '<', 35,
        '=', 17,
        '>', 36,
        '@', 26,
        '[', 33,
        ']', 34,
        '{', 14,
        '}', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('*' <= lookahead && lookahead <= '-')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(3);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_hex_number);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_address);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'i', 7,
        'j', 8,
        'm', 9,
        'n', 10,
        'o', 11,
        'p', 12,
        'r', 13,
        's', 14,
        't', 15,
        'x', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'c') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(22);
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'j') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 'm' ||
          lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        'c', 35,
        'e', 36,
        'g', 37,
        'l', 38,
        'm', 39,
        'n', 40,
        'v', 41,
        'r', 42,
        'z', 42,
      );
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == 't') ADVANCE(52);
      if (('1' <= lookahead && lookahead <= '8')) ADVANCE(32);
      END_STATE();
    case 14:
      ADVANCE_MAP(
        'b', 53,
        'e', 54,
        'h', 55,
        'p', 32,
        'r', 56,
        't', 57,
        'u', 58,
        'w', 59,
      );
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'c' ||
          lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(63);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 25:
      if (lookahead == 'c' ||
          lookahead == 'i' ||
          lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 30:
      if (lookahead == 'v') ADVANCE(68);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(70);
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'c' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'q') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 40:
      if (lookahead == 'e' ||
          lookahead == 'z') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 'c' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_mnemonic);
      END_STATE();
    case 43:
      if (lookahead == 'v') ADVANCE(71);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 45:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 46:
      if (lookahead == 'p' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 'g') ADVANCE(72);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 'l' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 54:
      if (lookahead == 'c' ||
          lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 55:
      if (lookahead == 'l' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 58:
      if (lookahead == 'b') ADVANCE(42);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 69:
      if (lookahead == 'z') ADVANCE(42);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == '8' ||
          lookahead == 'h' ||
          lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_directive_keyword);
      END_STATE();
    case 73:
      if (lookahead == 'h') ADVANCE(42);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'm') ADVANCE(82);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(83);
      END_STATE();
    case 77:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 79:
      if (lookahead == '1') ADVANCE(84);
      if (lookahead == '8') ADVANCE(72);
      END_STATE();
    case 80:
      if (lookahead == 'u') ADVANCE(85);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 82:
      if (lookahead == '_') ADVANCE(87);
      END_STATE();
    case 83:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 84:
      if (lookahead == '6') ADVANCE(72);
      END_STATE();
    case 85:
      if (lookahead == 'd') ADVANCE(89);
      END_STATE();
    case 86:
      if (lookahead == 'v') ADVANCE(90);
      END_STATE();
    case 87:
      if (lookahead == 'b') ADVANCE(91);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_struct_keyword);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 94:
      if (lookahead == 'k') ADVANCE(95);
      END_STATE();
    case 95:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_directive_keyword] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_struct_keyword] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_mnemonic] = ACTIONS(1),
    [sym_hex_number] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_char_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(68),
    [sym__line] = STATE(11),
    [sym__statement] = STATE(42),
    [sym_label] = STATE(42),
    [sym_local_label] = STATE(42),
    [sym_directive] = STATE(42),
    [sym_struct_directive] = STATE(42),
    [sym_instruction] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [sym_directive_keyword] = ACTIONS(15),
    [sym_struct_keyword] = ACTIONS(17),
    [sym_mnemonic] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_LT,
    STATE(41), 1,
      sym_operands,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    ACTIONS(27), 5,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_register,
    STATE(33), 6,
      sym__operand,
      sym_local_label_ref,
      sym_symbol_ref,
      sym_paren_expr,
      sym_bracket_expr,
      sym_cast,
  [45] = 6,
    ACTIONS(29), 1,
      anon_sym_AT,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(4), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(41), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [79] = 6,
    ACTIONS(29), 1,
      anon_sym_AT,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(5), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(45), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [113] = 6,
    ACTIONS(52), 1,
      anon_sym_AT,
    ACTIONS(55), 1,
      anon_sym_AMP,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(5), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(49), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [147] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 5,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_register,
    STATE(39), 6,
      sym__operand,
      sym_local_label_ref,
      sym_symbol_ref,
      sym_paren_expr,
      sym_bracket_expr,
      sym_cast,
  [187] = 2,
    ACTIONS(67), 1,
      anon_sym_AMP,
    ACTIONS(65), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [209] = 2,
    ACTIONS(71), 1,
      anon_sym_AMP,
    ACTIONS(69), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [231] = 2,
    ACTIONS(75), 1,
      anon_sym_AMP,
    ACTIONS(73), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [253] = 2,
    ACTIONS(79), 1,
      anon_sym_AMP,
    ACTIONS(77), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [275] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      sym_directive_keyword,
    ACTIONS(17), 1,
      sym_struct_keyword,
    ACTIONS(19), 1,
      sym_mnemonic,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym_newline,
    ACTIONS(85), 1,
      sym_comment,
    STATE(12), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(48), 6,
      sym__statement,
      sym_label,
      sym_local_label,
      sym_directive,
      sym_struct_directive,
      sym_instruction,
  [312] = 10,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(92), 1,
      sym_newline,
    ACTIONS(95), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(101), 1,
      sym_directive_keyword,
    ACTIONS(104), 1,
      sym_struct_keyword,
    ACTIONS(107), 1,
      sym_mnemonic,
    STATE(12), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(70), 6,
      sym__statement,
      sym_label,
      sym_local_label,
      sym_directive,
      sym_struct_directive,
      sym_instruction,
  [349] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 1,
      anon_sym_RBRACK,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(112), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(15), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [380] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    ACTIONS(124), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(16), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [411] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    ACTIONS(128), 1,
      sym_identifier,
    ACTIONS(130), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(17), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [442] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(128), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
    ACTIONS(130), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(17), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [473] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_AT,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    ACTIONS(148), 1,
      anon_sym_LT,
    ACTIONS(137), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(17), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(65), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [522] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_identifier,
    ACTIONS(153), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [540] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(157), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [558] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(26), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [581] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(24), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [604] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(22), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [627] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_AT,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(171), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(24), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [650] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(184), 8,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [667] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(24), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [690] = 2,
    ACTIONS(190), 2,
      sym_identifier,
      sym_mnemonic,
    ACTIONS(188), 6,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_DOT,
      sym_directive_keyword,
      sym_struct_keyword,
  [703] = 2,
    ACTIONS(194), 2,
      sym_identifier,
      sym_mnemonic,
    ACTIONS(192), 6,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_DOT,
      sym_directive_keyword,
      sym_struct_keyword,
  [716] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(198), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(30), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [734] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(202), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(31), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [752] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(31), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [770] = 3,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_operands_repeat1,
    ACTIONS(214), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [782] = 3,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_operands_repeat1,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [794] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 4,
      sym_newline,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [804] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_operands_repeat1,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [816] = 1,
    ACTIONS(227), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [823] = 1,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [830] = 1,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [837] = 1,
    ACTIONS(222), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [844] = 1,
    ACTIONS(157), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [851] = 1,
    ACTIONS(229), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [857] = 3,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 1,
      sym_newline,
    ACTIONS(233), 1,
      sym_comment,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 1,
      sym_newline,
  [877] = 1,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(239), 1,
      sym_newline,
  [893] = 1,
    ACTIONS(241), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [899] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_newline,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [909] = 3,
    ACTIONS(231), 1,
      sym_newline,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 1,
      sym_comment,
  [919] = 1,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [925] = 1,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [931] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_newline,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_newline,
  [955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_COLON,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identifier,
  [969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_newline,
  [976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_identifier,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
  [990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_identifier,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COLON,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_DOT,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LBRACK,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_GT,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
  [1039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COLON,
  [1053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
  [1060] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1067] = 2,
    ACTIONS(231), 1,
      sym_newline,
    ACTIONS(283), 1,
      sym_comment,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identifier,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1088] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DOT,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_identifier,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_GT,
  [1109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 79,
  [SMALL_STATE(5)] = 113,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 187,
  [SMALL_STATE(8)] = 209,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 253,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 312,
  [SMALL_STATE(13)] = 349,
  [SMALL_STATE(14)] = 380,
  [SMALL_STATE(15)] = 411,
  [SMALL_STATE(16)] = 442,
  [SMALL_STATE(17)] = 473,
  [SMALL_STATE(18)] = 504,
  [SMALL_STATE(19)] = 522,
  [SMALL_STATE(20)] = 540,
  [SMALL_STATE(21)] = 558,
  [SMALL_STATE(22)] = 581,
  [SMALL_STATE(23)] = 604,
  [SMALL_STATE(24)] = 627,
  [SMALL_STATE(25)] = 650,
  [SMALL_STATE(26)] = 667,
  [SMALL_STATE(27)] = 690,
  [SMALL_STATE(28)] = 703,
  [SMALL_STATE(29)] = 716,
  [SMALL_STATE(30)] = 734,
  [SMALL_STATE(31)] = 752,
  [SMALL_STATE(32)] = 770,
  [SMALL_STATE(33)] = 782,
  [SMALL_STATE(34)] = 794,
  [SMALL_STATE(35)] = 804,
  [SMALL_STATE(36)] = 816,
  [SMALL_STATE(37)] = 823,
  [SMALL_STATE(38)] = 830,
  [SMALL_STATE(39)] = 837,
  [SMALL_STATE(40)] = 844,
  [SMALL_STATE(41)] = 851,
  [SMALL_STATE(42)] = 857,
  [SMALL_STATE(43)] = 867,
  [SMALL_STATE(44)] = 877,
  [SMALL_STATE(45)] = 883,
  [SMALL_STATE(46)] = 893,
  [SMALL_STATE(47)] = 899,
  [SMALL_STATE(48)] = 909,
  [SMALL_STATE(49)] = 919,
  [SMALL_STATE(50)] = 925,
  [SMALL_STATE(51)] = 931,
  [SMALL_STATE(52)] = 941,
  [SMALL_STATE(53)] = 948,
  [SMALL_STATE(54)] = 955,
  [SMALL_STATE(55)] = 962,
  [SMALL_STATE(56)] = 969,
  [SMALL_STATE(57)] = 976,
  [SMALL_STATE(58)] = 983,
  [SMALL_STATE(59)] = 990,
  [SMALL_STATE(60)] = 997,
  [SMALL_STATE(61)] = 1004,
  [SMALL_STATE(62)] = 1011,
  [SMALL_STATE(63)] = 1018,
  [SMALL_STATE(64)] = 1025,
  [SMALL_STATE(65)] = 1032,
  [SMALL_STATE(66)] = 1039,
  [SMALL_STATE(67)] = 1046,
  [SMALL_STATE(68)] = 1053,
  [SMALL_STATE(69)] = 1060,
  [SMALL_STATE(70)] = 1067,
  [SMALL_STATE(71)] = 1074,
  [SMALL_STATE(72)] = 1081,
  [SMALL_STATE(73)] = 1088,
  [SMALL_STATE(74)] = 1095,
  [SMALL_STATE(75)] = 1102,
  [SMALL_STATE(76)] = 1109,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_ref, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_ref, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cast, 6, 0, 7),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cast, 6, 0, 7),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 6),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_label_ref, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_directive, 4, 0, 5),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_directive, 5, 0, 5),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_label, 3, 0, 4),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [279] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gero_asm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gero_asm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
