/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_newline = 2,
  sym_comment = 3,
  anon_sym_COLON = 4,
  sym_export_marker = 5,
  sym_directive_keyword = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_COMMA = 9,
  anon_sym_EQ = 10,
  sym_mnemonic = 11,
  sym_hex_number = 12,
  sym_address = 13,
  anon_sym_BANG = 14,
  sym_register = 15,
  anon_sym_AMP = 16,
  sym_operator = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_DOT = 24,
  sym_source_file = 25,
  sym__line = 26,
  sym__statement = 27,
  sym_label = 28,
  sym_directive = 29,
  sym__dir_tail = 30,
  sym_instruction = 31,
  sym_operands = 32,
  sym__operand = 33,
  sym_variable = 34,
  sym_register_ptr = 35,
  sym_paren_expr = 36,
  sym_addr_bracket = 37,
  sym_cast = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_directive_repeat1 = 40,
  aux_sym_operands_repeat1 = 41,
  aux_sym_paren_expr_repeat1 = 42,
  aux_sym_addr_bracket_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [sym_export_marker] = "export_marker",
  [sym_directive_keyword] = "directive_keyword",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_mnemonic] = "mnemonic",
  [sym_hex_number] = "hex_number",
  [sym_address] = "address",
  [anon_sym_BANG] = "!",
  [sym_register] = "register",
  [anon_sym_AMP] = "&",
  [sym_operator] = "operator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_directive] = "directive",
  [sym__dir_tail] = "_dir_tail",
  [sym_instruction] = "instruction",
  [sym_operands] = "operands",
  [sym__operand] = "_operand",
  [sym_variable] = "variable",
  [sym_register_ptr] = "register_ptr",
  [sym_paren_expr] = "paren_expr",
  [sym_addr_bracket] = "addr_bracket",
  [sym_cast] = "cast",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
  [aux_sym_operands_repeat1] = "operands_repeat1",
  [aux_sym_paren_expr_repeat1] = "paren_expr_repeat1",
  [aux_sym_addr_bracket_repeat1] = "addr_bracket_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_export_marker] = sym_export_marker,
  [sym_directive_keyword] = sym_directive_keyword,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_mnemonic] = sym_mnemonic,
  [sym_hex_number] = sym_hex_number,
  [sym_address] = sym_address,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_register] = sym_register,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_operator] = sym_operator,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_directive] = sym_directive,
  [sym__dir_tail] = sym__dir_tail,
  [sym_instruction] = sym_instruction,
  [sym_operands] = sym_operands,
  [sym__operand] = sym__operand,
  [sym_variable] = sym_variable,
  [sym_register_ptr] = sym_register_ptr,
  [sym_paren_expr] = sym_paren_expr,
  [sym_addr_bracket] = sym_addr_bracket,
  [sym_cast] = sym_cast,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
  [aux_sym_operands_repeat1] = aux_sym_operands_repeat1,
  [aux_sym_paren_expr_repeat1] = aux_sym_paren_expr_repeat1,
  [aux_sym_addr_bracket_repeat1] = aux_sym_addr_bracket_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_export_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_number] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__dir_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_operands] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_register_ptr] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_addr_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_cast] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operands_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paren_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_addr_bracket_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_export = 1,
  field_keyword = 2,
  field_mnemonic = 3,
  field_name = 4,
  field_object = 5,
  field_property = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_export] = "export",
  [field_keyword] = "keyword",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
  [1] =
    {field_mnemonic, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_export, 0},
    {field_keyword, 1},
  [5] =
    {field_object, 3},
    {field_property, 5},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 10,
  [21] = 21,
  [22] = 22,
  [23] = 17,
  [24] = 18,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 22,
  [35] = 21,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 45,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 53,
  [57] = 57,
  [58] = 58,
  [59] = 50,
  [60] = 60,
  [61] = 57,
  [62] = 54,
  [63] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 6,
        '\r', 1,
        '!', 23,
        '$', 2,
        '&', 24,
        '(', 26,
        ')', 27,
        '+', 10,
        ',', 13,
        '.', 32,
        ':', 9,
        ';', 7,
        '<', 30,
        '=', 14,
        '>', 31,
        '[', 28,
        ']', 29,
        '{', 11,
        '}', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('*' <= lookahead && lookahead <= '-')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(6);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 3:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 6,
        '\r', 1,
        '!', 23,
        '$', 2,
        '&', 24,
        '(', 26,
        ')', 27,
        ',', 13,
        ':', 9,
        ';', 7,
        '<', 30,
        '=', 14,
        ']', 29,
        '{', 11,
        '}', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('*' <= lookahead && lookahead <= '-')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '+') ADVANCE(10);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_export_marker);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_hex_number);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_address);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'i', 7,
        'j', 8,
        'l', 9,
        'm', 10,
        'n', 11,
        'o', 12,
        'p', 13,
        'r', 14,
        's', 15,
        'x', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(26);
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 'm' ||
          lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'g') ADVANCE(30);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == 'm') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead == 'z') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(35);
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(39);
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(43);
      if (lookahead == 's') ADVANCE(44);
      if (lookahead == 't') ADVANCE(45);
      if (('1' <= lookahead && lookahead <= '8')) ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(25);
      if (lookahead == 't') ADVANCE(46);
      if (lookahead == 'u') ADVANCE(47);
      if (lookahead == 'w') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead == 'c' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'q') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'e' ||
          lookahead == 'z') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_mnemonic);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 36:
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == 'v') ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 47:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 53:
      if (lookahead == 'v') ADVANCE(34);
      END_STATE();
    case 54:
      if (lookahead == 'v') ADVANCE(34);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == '8') ADVANCE(34);
      END_STATE();
    case 56:
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 59:
      if (lookahead == '1') ADVANCE(62);
      if (lookahead == '8') ADVANCE(61);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_directive_keyword);
      END_STATE();
    case 62:
      if (lookahead == '6') ADVANCE(61);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_export_marker] = ACTIONS(1),
    [sym_directive_keyword] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_mnemonic] = ACTIONS(1),
    [sym_hex_number] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym__line] = STATE(16),
    [sym__statement] = STATE(40),
    [sym_label] = STATE(40),
    [sym_directive] = STATE(40),
    [sym_instruction] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [sym_export_marker] = ACTIONS(13),
    [sym_directive_keyword] = ACTIONS(15),
    [sym_mnemonic] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(7), 4,
      sym__dir_tail,
      sym_variable,
      sym_addr_bracket,
      aux_sym_directive_repeat1,
    ACTIONS(21), 9,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_operator,
  [29] = 5,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(5), 4,
      sym__dir_tail,
      sym_variable,
      sym_addr_bracket,
      aux_sym_directive_repeat1,
    ACTIONS(29), 9,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_operator,
  [58] = 9,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_LT,
    STATE(42), 1,
      sym_operands,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    ACTIONS(35), 3,
      sym_hex_number,
      sym_address,
      sym_register,
    STATE(29), 6,
      sym__operand,
      sym_variable,
      sym_register_ptr,
      sym_paren_expr,
      sym_addr_bracket,
      sym_cast,
  [95] = 5,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(6), 4,
      sym__dir_tail,
      sym_variable,
      sym_addr_bracket,
      aux_sym_directive_repeat1,
    ACTIONS(45), 9,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_operator,
  [124] = 5,
    ACTIONS(52), 1,
      anon_sym_BANG,
    ACTIONS(55), 1,
      anon_sym_AMP,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(6), 4,
      sym__dir_tail,
      sym_variable,
      sym_addr_bracket,
      aux_sym_directive_repeat1,
    ACTIONS(49), 9,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_operator,
  [153] = 5,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(6), 4,
      sym__dir_tail,
      sym_variable,
      sym_addr_bracket,
      aux_sym_directive_repeat1,
    ACTIONS(45), 9,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_operator,
  [182] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_LT,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 3,
      sym_hex_number,
      sym_address,
      sym_register,
    STATE(33), 6,
      sym__operand,
      sym_variable,
      sym_register_ptr,
      sym_paren_expr,
      sym_addr_bracket,
      sym_cast,
  [214] = 2,
    ACTIONS(66), 1,
      anon_sym_AMP,
    ACTIONS(64), 13,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_BANG,
      sym_operator,
  [233] = 2,
    ACTIONS(70), 1,
      anon_sym_AMP,
    ACTIONS(68), 13,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_BANG,
      sym_operator,
  [252] = 2,
    ACTIONS(74), 1,
      anon_sym_AMP,
    ACTIONS(72), 13,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_BANG,
      sym_operator,
  [271] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_RBRACK,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(78), 3,
      sym_hex_number,
      sym_register,
      sym_operator,
    STATE(13), 4,
      sym_variable,
      sym_paren_expr,
      sym_cast,
      aux_sym_addr_bracket_repeat1,
  [301] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(92), 1,
      anon_sym_RBRACK,
    ACTIONS(90), 3,
      sym_hex_number,
      sym_register,
      sym_operator,
    STATE(15), 4,
      sym_variable,
      sym_paren_expr,
      sym_cast,
      aux_sym_addr_bracket_repeat1,
  [331] = 9,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_newline,
    ACTIONS(102), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_export_marker,
    ACTIONS(108), 1,
      sym_directive_keyword,
    ACTIONS(111), 1,
      sym_mnemonic,
    STATE(14), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(51), 4,
      sym__statement,
      sym_label,
      sym_directive,
      sym_instruction,
  [363] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_LPAREN,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    ACTIONS(128), 1,
      anon_sym_LT,
    ACTIONS(117), 3,
      sym_hex_number,
      sym_register,
      sym_operator,
    STATE(15), 4,
      sym_variable,
      sym_paren_expr,
      sym_cast,
      aux_sym_addr_bracket_repeat1,
  [393] = 9,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_export_marker,
    ACTIONS(15), 1,
      sym_directive_keyword,
    ACTIONS(17), 1,
      sym_mnemonic,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 1,
      sym_newline,
    ACTIONS(135), 1,
      sym_comment,
    STATE(14), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(39), 4,
      sym__statement,
      sym_label,
      sym_directive,
      sym_instruction,
  [425] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(137), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(19), 3,
      sym_variable,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [448] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    ACTIONS(141), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(17), 3,
      sym_variable,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [471] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_BANG,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(145), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(19), 3,
      sym_variable,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [494] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(68), 8,
      sym_hex_number,
      anon_sym_BANG,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(158), 8,
      sym_hex_number,
      anon_sym_BANG,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(162), 8,
      sym_hex_number,
      anon_sym_BANG,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [545] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(137), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(19), 3,
      sym_variable,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [568] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_BANG,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(166), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(23), 3,
      sym_variable,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [591] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(172), 7,
      sym_hex_number,
      anon_sym_BANG,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [607] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_export_marker,
      sym_directive_keyword,
      sym_mnemonic,
  [619] = 2,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_export_marker,
      sym_directive_keyword,
      sym_mnemonic,
  [631] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_operands_repeat1,
    ACTIONS(182), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [643] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_operands_repeat1,
    ACTIONS(186), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [655] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_operands_repeat1,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [667] = 1,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [674] = 1,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [681] = 1,
    ACTIONS(188), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [688] = 1,
    ACTIONS(162), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [695] = 1,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(197), 1,
      sym_newline,
  [712] = 1,
    ACTIONS(199), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym_newline,
  [728] = 3,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym_newline,
    ACTIONS(203), 1,
      sym_comment,
  [738] = 3,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym_newline,
    ACTIONS(205), 1,
      sym_comment,
  [748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym_newline,
  [758] = 1,
    ACTIONS(207), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_newline,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_register,
    ACTIONS(213), 1,
      anon_sym_LBRACK,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_DOT,
  [791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_newline,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_directive_keyword,
  [805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_newline,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DOT,
  [819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym_identifier,
  [826] = 2,
    ACTIONS(201), 1,
      sym_newline,
    ACTIONS(223), 1,
      sym_comment,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
  [840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
  [847] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_GT,
  [854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_LBRACK,
  [861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
  [868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_identifier,
  [875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_identifier,
  [889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_GT,
  [910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 95,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 214,
  [SMALL_STATE(10)] = 233,
  [SMALL_STATE(11)] = 252,
  [SMALL_STATE(12)] = 271,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 331,
  [SMALL_STATE(15)] = 363,
  [SMALL_STATE(16)] = 393,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 448,
  [SMALL_STATE(19)] = 471,
  [SMALL_STATE(20)] = 494,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 528,
  [SMALL_STATE(23)] = 545,
  [SMALL_STATE(24)] = 568,
  [SMALL_STATE(25)] = 591,
  [SMALL_STATE(26)] = 607,
  [SMALL_STATE(27)] = 619,
  [SMALL_STATE(28)] = 631,
  [SMALL_STATE(29)] = 643,
  [SMALL_STATE(30)] = 655,
  [SMALL_STATE(31)] = 667,
  [SMALL_STATE(32)] = 674,
  [SMALL_STATE(33)] = 681,
  [SMALL_STATE(34)] = 688,
  [SMALL_STATE(35)] = 695,
  [SMALL_STATE(36)] = 702,
  [SMALL_STATE(37)] = 712,
  [SMALL_STATE(38)] = 718,
  [SMALL_STATE(39)] = 728,
  [SMALL_STATE(40)] = 738,
  [SMALL_STATE(41)] = 748,
  [SMALL_STATE(42)] = 758,
  [SMALL_STATE(43)] = 764,
  [SMALL_STATE(44)] = 774,
  [SMALL_STATE(45)] = 784,
  [SMALL_STATE(46)] = 791,
  [SMALL_STATE(47)] = 798,
  [SMALL_STATE(48)] = 805,
  [SMALL_STATE(49)] = 812,
  [SMALL_STATE(50)] = 819,
  [SMALL_STATE(51)] = 826,
  [SMALL_STATE(52)] = 833,
  [SMALL_STATE(53)] = 840,
  [SMALL_STATE(54)] = 847,
  [SMALL_STATE(55)] = 854,
  [SMALL_STATE(56)] = 861,
  [SMALL_STATE(57)] = 868,
  [SMALL_STATE(58)] = 875,
  [SMALL_STATE(59)] = 882,
  [SMALL_STATE(60)] = 889,
  [SMALL_STATE(61)] = 896,
  [SMALL_STATE(62)] = 903,
  [SMALL_STATE(63)] = 910,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 4),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addr_bracket, 4, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addr_bracket, 4, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addr_bracket, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addr_bracket, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addr_bracket_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cast, 6, 0, 5),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cast, 6, 0, 5),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register_ptr, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gero_asm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
