/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_newline = 2,
  sym_comment = 3,
  anon_sym_COLON = 4,
  anon_sym_DOT = 5,
  sym_export_marker = 6,
  sym_directive_keyword = 7,
  anon_sym_LBRACE = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACE = 10,
  sym_struct_keyword = 11,
  anon_sym_EQ = 12,
  sym_mnemonic = 13,
  sym_hex_number = 14,
  sym_address = 15,
  anon_sym_AT = 16,
  sym_char_literal = 17,
  sym_string_literal = 18,
  sym_register = 19,
  anon_sym_AMP = 20,
  sym_operator = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  sym_source_file = 28,
  sym__line = 29,
  sym__statement = 30,
  sym_label = 31,
  sym_local_label = 32,
  sym_directive = 33,
  sym_struct_directive = 34,
  sym_struct_field = 35,
  sym__dir_tail = 36,
  sym_instruction = 37,
  sym_operands = 38,
  sym__operand = 39,
  sym_local_label_ref = 40,
  sym_symbol_ref = 41,
  sym_register_ptr = 42,
  sym_paren_expr = 43,
  sym_bracket_expr = 44,
  sym_cast = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_directive_repeat1 = 47,
  aux_sym_struct_directive_repeat1 = 48,
  aux_sym_operands_repeat1 = 49,
  aux_sym_paren_expr_repeat1 = 50,
  aux_sym_bracket_expr_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [sym_export_marker] = "export_marker",
  [sym_directive_keyword] = "directive_keyword",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [sym_struct_keyword] = "struct_keyword",
  [anon_sym_EQ] = "=",
  [sym_mnemonic] = "mnemonic",
  [sym_hex_number] = "hex_number",
  [sym_address] = "address",
  [anon_sym_AT] = "@",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [sym_register] = "register",
  [anon_sym_AMP] = "&",
  [sym_operator] = "operator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_local_label] = "local_label",
  [sym_directive] = "directive",
  [sym_struct_directive] = "struct_directive",
  [sym_struct_field] = "struct_field",
  [sym__dir_tail] = "_dir_tail",
  [sym_instruction] = "instruction",
  [sym_operands] = "operands",
  [sym__operand] = "_operand",
  [sym_local_label_ref] = "local_label_ref",
  [sym_symbol_ref] = "symbol_ref",
  [sym_register_ptr] = "register_ptr",
  [sym_paren_expr] = "paren_expr",
  [sym_bracket_expr] = "bracket_expr",
  [sym_cast] = "cast",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
  [aux_sym_struct_directive_repeat1] = "struct_directive_repeat1",
  [aux_sym_operands_repeat1] = "operands_repeat1",
  [aux_sym_paren_expr_repeat1] = "paren_expr_repeat1",
  [aux_sym_bracket_expr_repeat1] = "bracket_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_export_marker] = sym_export_marker,
  [sym_directive_keyword] = sym_directive_keyword,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_struct_keyword] = sym_struct_keyword,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_mnemonic] = sym_mnemonic,
  [sym_hex_number] = sym_hex_number,
  [sym_address] = sym_address,
  [anon_sym_AT] = anon_sym_AT,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_register] = sym_register,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_operator] = sym_operator,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_local_label] = sym_local_label,
  [sym_directive] = sym_directive,
  [sym_struct_directive] = sym_struct_directive,
  [sym_struct_field] = sym_struct_field,
  [sym__dir_tail] = sym__dir_tail,
  [sym_instruction] = sym_instruction,
  [sym_operands] = sym_operands,
  [sym__operand] = sym__operand,
  [sym_local_label_ref] = sym_local_label_ref,
  [sym_symbol_ref] = sym_symbol_ref,
  [sym_register_ptr] = sym_register_ptr,
  [sym_paren_expr] = sym_paren_expr,
  [sym_bracket_expr] = sym_bracket_expr,
  [sym_cast] = sym_cast,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
  [aux_sym_struct_directive_repeat1] = aux_sym_struct_directive_repeat1,
  [aux_sym_operands_repeat1] = aux_sym_operands_repeat1,
  [aux_sym_paren_expr_repeat1] = aux_sym_paren_expr_repeat1,
  [aux_sym_bracket_expr_repeat1] = aux_sym_bracket_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_export_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_struct_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_number] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_local_label] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__dir_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_operands] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym_local_label_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_register_ptr] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_cast] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operands_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paren_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bracket_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_export = 1,
  field_keyword = 2,
  field_mnemonic = 3,
  field_name = 4,
  field_object = 5,
  field_property = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_export] = "export",
  [field_keyword] = "keyword",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
  [1] =
    {field_mnemonic, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_export, 0},
    {field_keyword, 1},
  [5] =
    {field_name, 1},
  [6] =
    {field_keyword, 0},
    {field_name, 1},
  [8] =
    {field_name, 0},
    {field_type, 2},
  [10] =
    {field_object, 3},
    {field_property, 5},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 24,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 21,
  [39] = 39,
  [40] = 40,
  [41] = 27,
  [42] = 42,
  [43] = 22,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 56,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 72,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 66,
  [79] = 58,
  [80] = 59,
  [81] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '\n', 11,
        '\r', 1,
        '"', 2,
        '$', 7,
        '&', 32,
        '\'', 4,
        '(', 34,
        ')', 35,
        '+', 16,
        ',', 18,
        '.', 15,
        ':', 14,
        ';', 12,
        '<', 38,
        '=', 20,
        '>', 39,
        '@', 29,
        '[', 36,
        ']', 37,
        '{', 17,
        '}', 19,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('*' <= lookahead && lookahead <= '-')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(3);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '\n', 11,
        '\r', 1,
        '"', 2,
        '$', 7,
        '&', 32,
        '\'', 4,
        '(', 34,
        ')', 35,
        ',', 18,
        ':', 14,
        ';', 12,
        '<', 38,
        '=', 20,
        '@', 29,
        '[', 36,
        ']', 37,
        '{', 17,
        '}', 19,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('*' <= lookahead && lookahead <= '-')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_export_marker);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_hex_number);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_address);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'i', 7,
        'j', 8,
        'm', 9,
        'n', 10,
        'o', 11,
        'p', 12,
        'r', 13,
        's', 14,
        't', 15,
        'x', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'c') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(22);
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'j') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 'm' ||
          lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        'c', 35,
        'e', 36,
        'g', 37,
        'l', 38,
        'm', 39,
        'n', 40,
        'v', 41,
        'r', 42,
        'z', 42,
      );
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == 't') ADVANCE(52);
      if (('1' <= lookahead && lookahead <= '8')) ADVANCE(32);
      END_STATE();
    case 14:
      ADVANCE_MAP(
        'b', 53,
        'e', 54,
        'h', 55,
        'p', 32,
        'r', 56,
        't', 57,
        'u', 58,
        'w', 59,
      );
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'c' ||
          lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(63);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 25:
      if (lookahead == 'c' ||
          lookahead == 'i' ||
          lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 30:
      if (lookahead == 'v') ADVANCE(68);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(70);
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'c' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'q') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'e' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 40:
      if (lookahead == 'e' ||
          lookahead == 'z') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 'c' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_mnemonic);
      END_STATE();
    case 43:
      if (lookahead == 'v') ADVANCE(71);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 45:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 46:
      if (lookahead == 'p' ||
          lookahead == 't') ADVANCE(42);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 'g') ADVANCE(72);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 'l' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 54:
      if (lookahead == 'c' ||
          lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 55:
      if (lookahead == 'l' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 58:
      if (lookahead == 'b') ADVANCE(42);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 69:
      if (lookahead == 'z') ADVANCE(42);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_mnemonic);
      if (lookahead == '8' ||
          lookahead == 'h' ||
          lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_directive_keyword);
      END_STATE();
    case 73:
      if (lookahead == 'h') ADVANCE(42);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'm') ADVANCE(82);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(83);
      END_STATE();
    case 77:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 79:
      if (lookahead == '1') ADVANCE(84);
      if (lookahead == '8') ADVANCE(72);
      END_STATE();
    case 80:
      if (lookahead == 'u') ADVANCE(85);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 82:
      if (lookahead == '_') ADVANCE(87);
      END_STATE();
    case 83:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 84:
      if (lookahead == '6') ADVANCE(72);
      END_STATE();
    case 85:
      if (lookahead == 'd') ADVANCE(89);
      END_STATE();
    case 86:
      if (lookahead == 'v') ADVANCE(90);
      END_STATE();
    case 87:
      if (lookahead == 'b') ADVANCE(91);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_struct_keyword);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 94:
      if (lookahead == 'k') ADVANCE(95);
      END_STATE();
    case 95:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_export_marker] = ACTIONS(1),
    [sym_directive_keyword] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_struct_keyword] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_mnemonic] = ACTIONS(1),
    [sym_hex_number] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_char_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(71),
    [sym__line] = STATE(9),
    [sym__statement] = STATE(44),
    [sym_label] = STATE(44),
    [sym_local_label] = STATE(44),
    [sym_directive] = STATE(44),
    [sym_struct_directive] = STATE(44),
    [sym_instruction] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [sym_export_marker] = ACTIONS(15),
    [sym_directive_keyword] = ACTIONS(17),
    [sym_struct_keyword] = ACTIONS(19),
    [sym_mnemonic] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LT,
    STATE(48), 1,
      sym_operands,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    ACTIONS(29), 5,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_register,
    STATE(34), 7,
      sym__operand,
      sym_local_label_ref,
      sym_symbol_ref,
      sym_register_ptr,
      sym_paren_expr,
      sym_bracket_expr,
      sym_cast,
  [46] = 6,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(6), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(43), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [80] = 6,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(7), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(49), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [114] = 6,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(4), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(53), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [148] = 6,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(7), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(49), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [182] = 6,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(65), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
    STATE(7), 4,
      sym__dir_tail,
      sym_symbol_ref,
      sym_bracket_expr,
      aux_sym_directive_repeat1,
    ACTIONS(59), 11,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
  [216] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 5,
      sym_hex_number,
      sym_address,
      sym_char_literal,
      sym_string_literal,
      sym_register,
    STATE(42), 7,
      sym__operand,
      sym_local_label_ref,
      sym_symbol_ref,
      sym_register_ptr,
      sym_paren_expr,
      sym_bracket_expr,
      sym_cast,
  [257] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      sym_export_marker,
    ACTIONS(17), 1,
      sym_directive_keyword,
    ACTIONS(19), 1,
      sym_struct_keyword,
    ACTIONS(21), 1,
      sym_mnemonic,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym_newline,
    ACTIONS(79), 1,
      sym_comment,
    STATE(10), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(52), 6,
      sym__statement,
      sym_label,
      sym_local_label,
      sym_directive,
      sym_struct_directive,
      sym_instruction,
  [297] = 11,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym_newline,
    ACTIONS(89), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_export_marker,
    ACTIONS(98), 1,
      sym_directive_keyword,
    ACTIONS(101), 1,
      sym_struct_keyword,
    ACTIONS(104), 1,
      sym_mnemonic,
    STATE(10), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(69), 6,
      sym__statement,
      sym_label,
      sym_local_label,
      sym_directive,
      sym_struct_directive,
      sym_instruction,
  [337] = 2,
    ACTIONS(109), 1,
      anon_sym_AMP,
    ACTIONS(107), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [359] = 2,
    ACTIONS(113), 1,
      anon_sym_AMP,
    ACTIONS(111), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [381] = 2,
    ACTIONS(117), 1,
      anon_sym_AMP,
    ACTIONS(115), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [403] = 2,
    ACTIONS(121), 1,
      anon_sym_AMP,
    ACTIONS(119), 16,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_char_literal,
      sym_string_literal,
      sym_operator,
      anon_sym_LBRACK,
  [425] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(125), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(16), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [456] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    ACTIONS(137), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(18), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [487] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_RBRACK,
    ACTIONS(137), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(18), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [518] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_AT,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(146), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(18), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [549] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(162), 4,
      sym_hex_number,
      sym_address,
      sym_register,
      sym_operator,
    STATE(17), 4,
      sym_symbol_ref,
      sym_paren_expr,
      sym_cast,
      aux_sym_bracket_expr_repeat1,
  [580] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(107), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [598] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      sym_identifier,
    ACTIONS(166), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(170), 9,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [634] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(26), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [657] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(176), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(25), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [680] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(26), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [703] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_AT,
    ACTIONS(188), 1,
      anon_sym_LPAREN,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(182), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(26), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [726] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(195), 8,
      sym_hex_number,
      sym_address,
      anon_sym_AT,
      sym_register,
      sym_operator,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
      anon_sym_LT,
  [743] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_AT,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 3,
      sym_identifier,
      sym_hex_number,
      sym_operator,
    STATE(23), 3,
      sym_symbol_ref,
      sym_paren_expr,
      aux_sym_paren_expr_repeat1,
  [766] = 2,
    ACTIONS(203), 2,
      sym_identifier,
      sym_mnemonic,
    ACTIONS(201), 7,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_DOT,
      sym_export_marker,
      sym_directive_keyword,
      sym_struct_keyword,
  [780] = 2,
    ACTIONS(207), 2,
      sym_identifier,
      sym_mnemonic,
    ACTIONS(205), 7,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_DOT,
      sym_export_marker,
      sym_directive_keyword,
      sym_struct_keyword,
  [794] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    ACTIONS(211), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(32), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [812] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    ACTIONS(215), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(33), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [830] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(222), 2,
      sym_newline,
      anon_sym_COMMA,
    STATE(33), 2,
      sym_struct_field,
      aux_sym_struct_directive_repeat1,
  [848] = 3,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_operands_repeat1,
    ACTIONS(227), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [860] = 3,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_operands_repeat1,
    ACTIONS(231), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 4,
      sym_newline,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [882] = 3,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_operands_repeat1,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [894] = 1,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [901] = 1,
    ACTIONS(240), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [908] = 1,
    ACTIONS(242), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [915] = 1,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [922] = 1,
    ACTIONS(235), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [929] = 1,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
      anon_sym_COMMA,
  [936] = 3,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      sym_newline,
    ACTIONS(246), 1,
      sym_comment,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      sym_register,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
  [956] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      sym_newline,
  [966] = 1,
    ACTIONS(252), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [972] = 1,
    ACTIONS(254), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [978] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
    ACTIONS(258), 1,
      sym_newline,
  [988] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_newline,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
  [998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      sym_newline,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
  [1008] = 3,
    ACTIONS(244), 1,
      sym_newline,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
    ACTIONS(262), 1,
      sym_comment,
  [1018] = 1,
    ACTIONS(264), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [1024] = 1,
    ACTIONS(266), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [1030] = 1,
    ACTIONS(268), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [1036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_identifier,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [1050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_identifier,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_GT,
  [1064] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
  [1071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_newline,
  [1078] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_identifier,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_identifier,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_DOT,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      sym_newline,
  [1120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym_identifier,
  [1127] = 2,
    ACTIONS(244), 1,
      sym_newline,
    ACTIONS(292), 1,
      sym_comment,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_COLON,
  [1141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      ts_builtin_sym_end,
  [1148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_identifier,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COLON,
  [1162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
  [1169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_directive_keyword,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_COLON,
  [1190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_DOT,
  [1197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_identifier,
  [1204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_GT,
  [1211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 182,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 337,
  [SMALL_STATE(12)] = 359,
  [SMALL_STATE(13)] = 381,
  [SMALL_STATE(14)] = 403,
  [SMALL_STATE(15)] = 425,
  [SMALL_STATE(16)] = 456,
  [SMALL_STATE(17)] = 487,
  [SMALL_STATE(18)] = 518,
  [SMALL_STATE(19)] = 549,
  [SMALL_STATE(20)] = 580,
  [SMALL_STATE(21)] = 598,
  [SMALL_STATE(22)] = 616,
  [SMALL_STATE(23)] = 634,
  [SMALL_STATE(24)] = 657,
  [SMALL_STATE(25)] = 680,
  [SMALL_STATE(26)] = 703,
  [SMALL_STATE(27)] = 726,
  [SMALL_STATE(28)] = 743,
  [SMALL_STATE(29)] = 766,
  [SMALL_STATE(30)] = 780,
  [SMALL_STATE(31)] = 794,
  [SMALL_STATE(32)] = 812,
  [SMALL_STATE(33)] = 830,
  [SMALL_STATE(34)] = 848,
  [SMALL_STATE(35)] = 860,
  [SMALL_STATE(36)] = 872,
  [SMALL_STATE(37)] = 882,
  [SMALL_STATE(38)] = 894,
  [SMALL_STATE(39)] = 901,
  [SMALL_STATE(40)] = 908,
  [SMALL_STATE(41)] = 915,
  [SMALL_STATE(42)] = 922,
  [SMALL_STATE(43)] = 929,
  [SMALL_STATE(44)] = 936,
  [SMALL_STATE(45)] = 946,
  [SMALL_STATE(46)] = 956,
  [SMALL_STATE(47)] = 966,
  [SMALL_STATE(48)] = 972,
  [SMALL_STATE(49)] = 978,
  [SMALL_STATE(50)] = 988,
  [SMALL_STATE(51)] = 998,
  [SMALL_STATE(52)] = 1008,
  [SMALL_STATE(53)] = 1018,
  [SMALL_STATE(54)] = 1024,
  [SMALL_STATE(55)] = 1030,
  [SMALL_STATE(56)] = 1036,
  [SMALL_STATE(57)] = 1043,
  [SMALL_STATE(58)] = 1050,
  [SMALL_STATE(59)] = 1057,
  [SMALL_STATE(60)] = 1064,
  [SMALL_STATE(61)] = 1071,
  [SMALL_STATE(62)] = 1078,
  [SMALL_STATE(63)] = 1085,
  [SMALL_STATE(64)] = 1092,
  [SMALL_STATE(65)] = 1099,
  [SMALL_STATE(66)] = 1106,
  [SMALL_STATE(67)] = 1113,
  [SMALL_STATE(68)] = 1120,
  [SMALL_STATE(69)] = 1127,
  [SMALL_STATE(70)] = 1134,
  [SMALL_STATE(71)] = 1141,
  [SMALL_STATE(72)] = 1148,
  [SMALL_STATE(73)] = 1155,
  [SMALL_STATE(74)] = 1162,
  [SMALL_STATE(75)] = 1169,
  [SMALL_STATE(76)] = 1176,
  [SMALL_STATE(77)] = 1183,
  [SMALL_STATE(78)] = 1190,
  [SMALL_STATE(79)] = 1197,
  [SMALL_STATE(80)] = 1204,
  [SMALL_STATE(81)] = 1211,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_ref, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_ref, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expr, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expr, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paren_expr_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cast, 6, 0, 8),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cast, 6, 0, 8),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_directive_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 7),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operands_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register_ptr, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_label_ref, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_directive, 4, 0, 6),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_label, 3, 0, 5),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_directive, 5, 0, 6),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [296] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gero_asm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gero_asm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
